### PR TITLE
[Ng2LocationConfig] get baseHref from LocationStrategy.

### PR DESCRIPTION
**Pull request by aitboudad**

### CODE REVIEW

**Comment by christopherthielen** [comment]
Can you check the failed build? 
https://travis-ci.org/ui-router/ng2/jobs/194437588

Looks like `locationStrategy` should be `_ locationStrategy`

**Comment by aitboudad** [comment]
it should pass now

**Comment by christopherthielen** [comment]
Thanks a lot!  
Did this bug break your app?

**Comment by aitboudad** [comment]
yep, in `angular-universal` but I'm using a workaround right now until  `1.0.0-beta.5`

**Pull request merged**
